from pathlib import Path
import re
import sys

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else '.')


def read(rel):
    return (ROOT/rel).read_text(encoding='utf-8')

def write(rel, text):
    (ROOT/rel).write_text(text, encoding='utf-8', newline='\n')

def rep(text, old, new, label, count=1):
    n = text.count(old)
    if n != count:
        raise RuntimeError(f'{label}: expected {count} occurrences, found {n}')
    return text.replace(old, new, count)

def insert_before(text, marker, payload, label):
    if marker not in text:
        raise RuntimeError(f'{label}: marker not found')
    return text.replace(marker, payload + marker, 1)

def extract_balanced_function(text, start_marker):
    start = text.find(start_marker)
    if start < 0:
        raise RuntimeError(f'function marker not found: {start_marker}')
    brace = text.find('{', start)
    if brace < 0:
        raise RuntimeError('opening brace not found')
    depth = 0
    i = brace
    in_str = False
    esc = False
    while i < len(text):
        ch = text[i]
        if in_str:
            if esc:
                esc = False
            elif ch == '\\':
                esc = True
            elif ch == '"':
                in_str = False
        else:
            if ch == '"':
                in_str = True
            elif ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0:
                    return start, i + 1, text[start:i+1]
        i += 1
    raise RuntimeError('unterminated function')

hlsl_path = 'src/d3d12/frame_synthesis.hlsl'
hlsl = read(hlsl_path)
hlsl = rep(hlsl, '    uint RepeatedCapture;\n};', '''    uint SynthesisControl;\n};\n\nbool repeated_capture_enabled() {\n    return (SynthesisControl & 1U) != 0U;\n}\n\nfloat interpolation_alpha() {\n    uint encoded = (SynthesisControl >> 8U) & 0xffU;\n    return encoded == 0U ? 0.5 : float(encoded) / 256.0;\n}''', 'shader control')
hlsl = hlsl.replace('RepeatedCapture == 0', '!repeated_capture_enabled()')
hlsl = hlsl.replace('RepeatedCapture != 0', 'repeated_capture_enabled()')
hlsl = rep(hlsl, '''            if (preserve_stationary) {\n                output_color = saturate(0.5 * (current_fallback.color +\n                    sample_previous_target(pixel, Slice, ViewIndex).color));\n            } else {''', '''            if (preserve_stationary) {\n                const float alpha = interpolation_alpha();\n                output_color = saturate(lerp(\n                    sample_previous_target(pixel, Slice, ViewIndex).color,\n                    current_fallback.color,\n                    alpha));\n            } else {''', 'stationary alpha')
hlsl = rep(hlsl, '''                        float2 target_displacement =\n                            previous_endpoint.coordinate - current_endpoint;\n                        current_endpoint = pixel - 0.5 * target_displacement;''', '''                        float2 target_displacement =\n                            previous_endpoint.coordinate - current_endpoint;\n                        current_endpoint = pixel -\n                            (1.0 - interpolation_alpha()) * target_displacement;''', 'game motion alpha')
hlsl = rep(hlsl, '''                    previous_sample = sample_previous_target(\n                        pixel + residual_backward * 0.5, Slice, ViewIndex);\n                    current_sample = sample_current_target(\n                        pixel - residual_backward * 0.5, Slice, ViewIndex);''', '''                    const float alpha = interpolation_alpha();\n                    previous_sample = sample_previous_target(\n                        pixel + residual_backward * alpha, Slice, ViewIndex);\n                    current_sample = sample_current_target(\n                        pixel - residual_backward * (1.0 - alpha), Slice, ViewIndex);''', 'flow warp alpha')
hlsl = rep(hlsl, '''                    float4 flow_midpoint = 0.5 * (\n                        previous_sample.color + current_sample.color);''', '''                    const float alpha = interpolation_alpha();\n                    float4 flow_midpoint = lerp(\n                        previous_sample.color, current_sample.color, alpha);''', 'flow blend alpha')
hlsl = rep(hlsl, '''                    float4 stable_midpoint = 0.5 * (\n                        sample_previous_target(pixel, Slice, ViewIndex).color +\n                        current_fallback.color);''', '''                    float4 stable_midpoint = lerp(\n                        sample_previous_target(pixel, Slice, ViewIndex).color,\n                        current_fallback.color,\n                        alpha);''', 'stable blend alpha')
write(hlsl_path, hlsl)

hpp_path = 'include/xrfg/d3d12_frame_synthesizer.hpp'
hpp = read(hpp_path)
marker = '''    [[nodiscard]] HRESULT submit_pair(\n        const D3D12HistoryCaptureTicket& current,\n        std::span<const D3D12ReprojectionView> current_source_views,\n        std::span<const D3D12ReprojectionView> synthetic_target_views,\n        std::uint32_t synthetic_destination_index,\n        std::uint32_t current_destination_index,\n        D3D12FrameSynthesisTicket* ticket,\n        std::optional<OverlayPlacement> debug_marker = std::nullopt,\n        std::shared_ptr<const DlssMotionVectorSet> motion_vectors = {}) noexcept;\n'''
if marker not in hpp:
    raise RuntimeError('public submit_pair declaration not found')
hpp = hpp.replace(marker, marker + '''\n    // NVIDIA-only 4x prototype: one A/B optical-flow calculation feeds three\n    // synthesis outputs at alpha 0.25, 0.50 and 0.75.\n    [[nodiscard]] HRESULT submit_quad(\n        const D3D12HistoryCaptureTicket& current,\n        std::span<const D3D12ReprojectionView> current_source_views,\n        std::span<const D3D12ReprojectionView> synthetic_target_views,\n        std::span<const std::uint32_t> synthetic_destination_indices,\n        std::uint32_t current_destination_index,\n        D3D12FrameSynthesisTicket* ticket,\n        std::optional<OverlayPlacement> debug_marker = std::nullopt,\n        std::shared_ptr<const DlssMotionVectorSet> motion_vectors = {}) noexcept;\n''', 1)
write(hpp_path, hpp)

cpp_path = 'src/d3d12/d3d12_frame_synthesizer.cpp'
cpp = read(cpp_path)
start, end, fn = extract_balanced_function(cpp, '    [[nodiscard]] HRESULT record_nvidia_pair(')
quad = fn.replace('record_nvidia_pair(', 'record_nvidia_quad(', 1)
quad = quad.replace('        std::uint32_t synthetic_destination_index,\n', '        std::span<const std::uint32_t> synthetic_destination_indices,\n', 1)
quad = quad.replace('        if (slot.synthesis_command_list == nullptr) {\n            return E_UNEXPECTED;\n        }', '        if (slot.synthesis_command_list == nullptr) {\n            return E_UNEXPECTED;\n        }\n        if (synthetic_destination_indices.size() != 3) {\n            return E_INVALIDARG;\n        }', 1)
old_draw = '''        const UINT first_rtv = synthetic_destination_index *\n            image_description.DepthOrArraySize;\n        for (UINT view_index = 0;\n             view_index < static_cast<UINT>(target_views.size());\n             ++view_index) {\n            const UINT slice = resolved_array_slice(\n                target_views[view_index],\n                view_index,\n                target_views.size(),\n                image_description.DepthOrArraySize);\n            parameters.slice = slice;\n            parameters.view_index = view_index;\n            const D3D12_GPU_DESCRIPTOR_HANDLE block = offset_gpu_handle(\n                gpu_start,\n                slice * kDescriptorBlockSize,\n                descriptor_increment);\n            synthesis->SetGraphicsRootDescriptorTable(0, block);\n            synthesis->SetGraphicsRootDescriptorTable(\n                1,\n                offset_gpu_handle(\n                    block,\n                    kSrvDescriptorCount,\n                    descriptor_increment));\n            synthesis->SetGraphicsRoot32BitConstants(\n                2,\n                kSynthesisConstantCount,\n                &parameters,\n                0);\n            const D3D12_CPU_DESCRIPTOR_HANDLE rtv = offset_cpu_handle(\n                rtv_start,\n                first_rtv + slice,\n                rtv_increment);\n            synthesis->OMSetRenderTargets(1, &rtv, FALSE, nullptr);\n            set_viewport_and_scissor(\n                synthesis,\n                target_views[view_index].image_rect,\n                static_cast<UINT>(image_description.Width),\n                image_description.Height);\n            synthesis->DrawInstanced(3, 1, 0, 0);\n            clear_synthetic_marker(synthesis, rtv, target_views[view_index],\n                static_cast<UINT>(image_description.Width), image_description.Height, debug_marker);\n        }'''
new_draw = '''        static constexpr std::array<UINT, 3> kAlpha256{64U, 128U, 192U};\n        for (std::size_t output_index = 0; output_index < synthetic_destination_indices.size(); ++output_index) {\n            parameters.repeated_capture = kAlpha256[output_index] << 8U;\n            const UINT first_rtv = synthetic_destination_indices[output_index] * image_description.DepthOrArraySize;\n            for (UINT view_index = 0; view_index < static_cast<UINT>(target_views.size()); ++view_index) {\n                const UINT slice = resolved_array_slice(target_views[view_index], view_index, target_views.size(), image_description.DepthOrArraySize);\n                parameters.slice = slice;\n                parameters.view_index = view_index;\n                const D3D12_GPU_DESCRIPTOR_HANDLE block = offset_gpu_handle(gpu_start, slice * kDescriptorBlockSize, descriptor_increment);\n                synthesis->SetGraphicsRootDescriptorTable(0, block);\n                synthesis->SetGraphicsRootDescriptorTable(1, offset_gpu_handle(block, kSrvDescriptorCount, descriptor_increment));\n                synthesis->SetGraphicsRoot32BitConstants(2, kSynthesisConstantCount, &parameters, 0);\n                const D3D12_CPU_DESCRIPTOR_HANDLE rtv = offset_cpu_handle(rtv_start, first_rtv + slice, rtv_increment);\n                synthesis->OMSetRenderTargets(1, &rtv, FALSE, nullptr);\n                set_viewport_and_scissor(synthesis, target_views[view_index].image_rect, static_cast<UINT>(image_description.Width), image_description.Height);\n                synthesis->DrawInstanced(3, 1, 0, 0);\n                clear_synthetic_marker(synthesis, rtv, target_views[view_index], static_cast<UINT>(image_description.Width), image_description.Height, debug_marker);\n            }\n        }\n        parameters.repeated_capture = 0;'''
if old_draw not in quad:
    raise RuntimeError('nvidia draw block not found in cloned function')
quad = quad.replace(old_draw, new_draw, 1)
cpp = cpp[:end] + '\n\n' + quad + cpp[end:]
start, end, fn = extract_balanced_function(cpp, '    [[nodiscard]] HRESULT record_repeated_pair(')
quad_rep = fn.replace('record_repeated_pair(', 'record_repeated_quad(', 1).replace('        std::uint32_t synthetic_destination_index,\n', '        std::span<const std::uint32_t> synthetic_destination_indices,\n', 1)
old = '''        const UINT first_rtv = synthetic_destination_index *\n            image_description.DepthOrArraySize;\n        for (UINT view_index = 0;\n             view_index < static_cast<UINT>(target_views.size());\n             ++view_index) {\n            const UINT slice = resolved_array_slice(\n                target_views[view_index],\n                view_index,\n                target_views.size(),\n                image_description.DepthOrArraySize);\n            parameters.slice = slice;\n            parameters.view_index = view_index;\n            const UINT descriptor_base =\n                backend == D3D12OpticalFlowBackend::nvidia\n                    ? slice * kDescriptorBlockSize\n                    : 0;\n            const D3D12_GPU_DESCRIPTOR_HANDLE block = offset_gpu_handle(\n                gpu_start,\n                descriptor_base,\n                descriptor_increment);\n            slot.command_list->SetGraphicsRootDescriptorTable(0, block);\n            slot.command_list->SetGraphicsRootDescriptorTable(\n                1,\n                offset_gpu_handle(\n                    block,\n                    kSrvDescriptorCount,\n                    descriptor_increment));\n            slot.command_list->SetGraphicsRoot32BitConstants(\n                2,\n                kSynthesisConstantCount,\n                &parameters,\n                0);\n            const D3D12_CPU_DESCRIPTOR_HANDLE rtv = offset_cpu_handle(\n                rtv_start,\n                first_rtv + slice,\n                rtv_increment);\n            slot.command_list->OMSetRenderTargets(1, &rtv, FALSE, nullptr);\n            set_viewport_and_scissor(\n                slot.command_list.Get(),\n                target_views[view_index].image_rect,\n                static_cast<UINT>(image_description.Width),\n                image_description.Height);\n            slot.command_list->DrawInstanced(3, 1, 0, 0);\n            clear_synthetic_marker(slot.command_list.Get(), rtv, target_views[view_index],\n                static_cast<UINT>(image_description.Width), image_description.Height, debug_marker);\n        }'''
new = '''        if (synthetic_destination_indices.size() != 3) return E_INVALIDARG;\n        static constexpr std::array<UINT, 3> kAlpha256{64U, 128U, 192U};\n        for (std::size_t output_index = 0; output_index < synthetic_destination_indices.size(); ++output_index) {\n            parameters.repeated_capture = 1U | (kAlpha256[output_index] << 8U);\n            const UINT first_rtv = synthetic_destination_indices[output_index] * image_description.DepthOrArraySize;\n            for (UINT view_index = 0; view_index < static_cast<UINT>(target_views.size()); ++view_index) {\n                const UINT slice = resolved_array_slice(target_views[view_index], view_index, target_views.size(), image_description.DepthOrArraySize);\n                parameters.slice = slice; parameters.view_index = view_index;\n                const UINT descriptor_base = backend == D3D12OpticalFlowBackend::nvidia ? slice * kDescriptorBlockSize : 0;\n                const D3D12_GPU_DESCRIPTOR_HANDLE block = offset_gpu_handle(gpu_start, descriptor_base, descriptor_increment);\n                slot.command_list->SetGraphicsRootDescriptorTable(0, block);\n                slot.command_list->SetGraphicsRootDescriptorTable(1, offset_gpu_handle(block, kSrvDescriptorCount, descriptor_increment));\n                slot.command_list->SetGraphicsRoot32BitConstants(2, kSynthesisConstantCount, &parameters, 0);\n                const D3D12_CPU_DESCRIPTOR_HANDLE rtv = offset_cpu_handle(rtv_start, first_rtv + slice, rtv_increment);\n                slot.command_list->OMSetRenderTargets(1, &rtv, FALSE, nullptr);\n                set_viewport_and_scissor(slot.command_list.Get(), target_views[view_index].image_rect, static_cast<UINT>(image_description.Width), image_description.Height);\n                slot.command_list->DrawInstanced(3, 1, 0, 0);\n                clear_synthetic_marker(slot.command_list.Get(), rtv, target_views[view_index], static_cast<UINT>(image_description.Width), image_description.Height, debug_marker);\n            }\n        }'''
if old not in quad_rep: raise RuntimeError('repeated draw block not found')
quad_rep = quad_rep.replace(old, new, 1)
cpp = cpp[:end] + '\n\n' + quad_rep + cpp[end:]
start, end, fn = extract_balanced_function(cpp, '    [[nodiscard]] HRESULT submit_pair(\n')
submit = fn.replace('submit_pair(', 'submit_quad(', 1).replace('        std::uint32_t synthetic_destination_index,\n', '        std::span<const std::uint32_t> synthetic_destination_indices,\n', 1)
needle = '''        if (output_ticket == nullptr) {\n            return E_POINTER;\n        }\n        *output_ticket = {};'''
submit = rep(submit, needle, needle + '''\n        if (backend != D3D12OpticalFlowBackend::nvidia || synthetic_destination_indices.size() != 3) return E_INVALIDARG;\n        for (std::size_t i = 0; i < synthetic_destination_indices.size(); ++i) {\n            if (synthetic_destination_indices[i] >= synthetic_destinations.size()) return E_INVALIDARG;\n            for (std::size_t j = 0; j < i; ++j) if (synthetic_destination_indices[i] == synthetic_destination_indices[j]) return E_INVALIDARG;\n        }''', 'submit quad validation')
submit = submit.replace('            synthetic_destination_index >= synthetic_destinations.size() ||\n', '', 1)
submit = rep(submit, '''        result = destination_available(\n            synthetic_destinations[synthetic_destination_index]);\n        if (FAILED(result)) {\n            return result;\n        }''', '''        for (const std::uint32_t synthetic_destination_index : synthetic_destination_indices) {\n            result = destination_available(synthetic_destinations[synthetic_destination_index]);\n            if (FAILED(result)) return result;\n        }''', 'quad availability')
submit = rep(submit, '''            ID3D12Resource* const synthetic_destination =\n                synthetic_destinations[synthetic_destination_index].resource.Get();\n            ID3D12Resource* const current_destination =\n                current_destinations[current_destination_index].resource.Get();\n            if (repeated_resource == synthetic_destination ||\n                repeated_resource == current_destination) {\n                return E_INVALIDARG;\n            }''', '''            ID3D12Resource* const current_destination = current_destinations[current_destination_index].resource.Get();\n            if (repeated_resource == current_destination) return E_INVALIDARG;\n            for (const std::uint32_t synthetic_destination_index : synthetic_destination_indices)\n                if (repeated_resource == synthetic_destinations[synthetic_destination_index].resource.Get()) return E_INVALIDARG;''', 'quad repeated collision')
submit = submit.replace('            result = record_repeated_pair(\n', '            result = record_repeated_quad(\n', 1).replace('                synthetic_destination_index,\n                current_destination_index,', '                synthetic_destination_indices,\n                current_destination_index,', 1)
submit = rep(submit, '            synthetic_destinations[synthetic_destination_index].fence_value = fence_value;', '            for (const std::uint32_t synthetic_destination_index : synthetic_destination_indices) synthetic_destinations[synthetic_destination_index].fence_value = fence_value;', 'quad repeated fences')
submit = submit.replace('                synthetic_destination_index;\n            output_ticket->current_destination_index', '                synthetic_destination_indices.front();\n            output_ticket->current_destination_index', 1)
submit = rep(submit, '''        ID3D12Resource* const synthetic_destination =\n            synthetic_destinations[synthetic_destination_index].resource.Get();\n        ID3D12Resource* const current_destination =\n            current_destinations[current_destination_index].resource.Get();\n        if (previous.resource.Get() == next.resource.Get() ||\n            previous.resource.Get() == synthetic_destination ||\n            previous.resource.Get() == current_destination ||\n            next.resource.Get() == synthetic_destination ||\n            next.resource.Get() == current_destination) {\n            cancel_next();\n            return E_INVALIDARG;\n        }''', '''        ID3D12Resource* const current_destination = current_destinations[current_destination_index].resource.Get();\n        if (previous.resource.Get() == next.resource.Get() || previous.resource.Get() == current_destination || next.resource.Get() == current_destination) { cancel_next(); return E_INVALIDARG; }\n        for (const std::uint32_t synthetic_destination_index : synthetic_destination_indices) {\n            ID3D12Resource* const synthetic_destination = synthetic_destinations[synthetic_destination_index].resource.Get();\n            if (previous.resource.Get() == synthetic_destination || next.resource.Get() == synthetic_destination) { cancel_next(); return E_INVALIDARG; }\n        }''', 'quad normal collision')
submit = rep(submit, '''        bool used_game_motion = false;\n        result = record_pair(\n            slot,\n            previous,\n            next,\n            synthetic_target_views,\n            synthetic_destination_index,\n            current_destination_index,\n            debug_marker,\n            &used_game_motion);''', '''        result = record_nvidia_quad(\n            slot, previous, next, synthetic_target_views, synthetic_destination_indices, current_destination_index, debug_marker);''', 'quad record')
submit = rep(submit, '''        result = backend == D3D12OpticalFlowBackend::nvidia && !used_game_motion\n                     ? execute_nvidia_and_signal(slot, &next, &fence_value)\n                     : execute_and_signal(slot, &next, &fence_value);''', '        result = execute_nvidia_and_signal(slot, &next, &fence_value);', 'quad execute')
submit = submit.replace('        if (used_game_motion) report_dlss_motion_vector_use();\n', '', 1)
submit = rep(submit, '        synthetic_destinations[synthetic_destination_index].fence_value = fence_value;', '        for (const std::uint32_t synthetic_destination_index : synthetic_destination_indices) synthetic_destinations[synthetic_destination_index].fence_value = fence_value;', 'quad normal fences')
submit = submit.replace('        output_ticket->synthetic_destination_index = synthetic_destination_index;\n', '        output_ticket->synthetic_destination_index = synthetic_destination_indices.front();\n', 1)
cpp = cpp[:end] + '\n\n' + submit + cpp[end:]
start, end, fn = extract_balanced_function(cpp, 'HRESULT D3D12FrameSynthesizer::submit_pair(\n')
wrapper = fn.replace('D3D12FrameSynthesizer::submit_pair(', 'D3D12FrameSynthesizer::submit_quad(', 1).replace('    std::uint32_t synthetic_destination_index,\n', '    std::span<const std::uint32_t> synthetic_destination_indices,\n', 1).replace('        return impl_->submit_pair(\n', '        return impl_->submit_quad(\n', 1).replace('            synthetic_destination_index,\n', '            synthetic_destination_indices,\n', 1)
cpp = cpp[:end] + '\n\n' + wrapper + cpp[end:]
write(cpp_path, cpp)

layer_path = 'src/layer/openxr_layer.cpp'
layer = read(layer_path)
layer = rep(layer, '    PrivateSwapchainState synthetic;\n    std::shared_ptr<xrfg::D3D12FrameSynthesizer> synthesizer;', '    PrivateSwapchainState synthetic;\n    std::array<PrivateSwapchainState, 2> additional_synthetic{};\n    std::uint32_t synthetic_images_per_slot{};\n    std::shared_ptr<xrfg::D3D12FrameSynthesizer> synthesizer;', 'generation state')
layer = rep(layer, '        static_cast<void>(release_private_image(dispatch, generation->synthetic));\n        for (PrivateSwapchainState& image : generation->current) {', '        static_cast<void>(release_private_image(dispatch, generation->synthetic));\n        for (PrivateSwapchainState& image : generation->additional_synthetic) static_cast<void>(release_private_image(dispatch, image));\n        for (PrivateSwapchainState& image : generation->current) {', 'destroy release extras')
layer = rep(layer, '''        std::array<PrivateSwapchainState*, kCurrentSlotCount + 1> owned{};\n        owned[0] = &generation->synthetic;\n        for (std::size_t slot = 0; slot < kCurrentSlotCount; ++slot) {\n            owned[slot + 1] = &generation->current[slot];\n        }''', '''        std::array<PrivateSwapchainState*, kCurrentSlotCount + 3> owned{};\n        owned[0] = &generation->synthetic; owned[1] = &generation->additional_synthetic[0]; owned[2] = &generation->additional_synthetic[1];\n        for (std::size_t slot = 0; slot < kCurrentSlotCount; ++slot) owned[slot + 3] = &generation->current[slot];''', 'destroy owned extras')
layer = layer.replace('    CreatedPrivateSwapchain synthetic;\n    if (failure_reason != nullptr) {', '    CreatedPrivateSwapchain synthetic;\n    std::array<CreatedPrivateSwapchain, 2> additional_synthetic{};\n    if (failure_reason != nullptr) {', 2)
old = '''        if (!create_private_swapchain(state, private_info, &synthetic)) {\n            if (failure_reason != nullptr) {\n                *failure_reason =\n                    SwapchainEligibilityReason::synthetic_private_swapchain_failed;\n            }\n            destroy_current_ring(dispatch, &current);\n            return nullptr;\n        }'''
new = old + '''\n        for (CreatedPrivateSwapchain& extra : additional_synthetic) {\n            if (!create_private_swapchain(state, private_info, &extra)) {\n                if (failure_reason != nullptr) *failure_reason = SwapchainEligibilityReason::synthetic_private_swapchain_failed;\n                if (synthetic.state.handle != XR_NULL_HANDLE) { static_cast<void>(dispatch->destroy_swapchain(synthetic.state.handle)); synthetic.state.handle = XR_NULL_HANDLE; }\n                for (CreatedPrivateSwapchain& created : additional_synthetic) if (created.state.handle != XR_NULL_HANDLE) { static_cast<void>(dispatch->destroy_swapchain(created.state.handle)); created.state.handle = XR_NULL_HANDLE; }\n                destroy_current_ring(dispatch, &current); return nullptr;\n            }\n        }'''
layer = rep(layer, old, new, 'd3d12 create extras')
marker = '        auto synthesizer = std::make_shared<xrfg::D3D12FrameSynthesizer>();\n        const xrfg::D3D12OpticalFlowBackend backend =\n            state->session->optical_flow_backend;'
layer = rep(layer, marker, '''        std::vector<ID3D12Resource*> all_synthetic_d3d12 = synthetic.d3d12_resources;\n        const std::uint32_t synthetic_images_per_slot = static_cast<std::uint32_t>(synthetic.d3d12_resources.size());\n        for (const CreatedPrivateSwapchain& extra : additional_synthetic) {\n            if (extra.d3d12_resources.size() != synthetic.d3d12_resources.size()) return nullptr;\n            all_synthetic_d3d12.insert(all_synthetic_d3d12.end(), extra.d3d12_resources.begin(), extra.d3d12_resources.end());\n        }\n\n''' + marker, 'd3d12 flatten extras')
layer = rep(layer, '            std::span<ID3D12Resource* const>(\n                synthetic.d3d12_resources.data(),\n                synthetic.d3d12_resources.size()),', '            std::span<ID3D12Resource* const>(all_synthetic_d3d12.data(), all_synthetic_d3d12.size()),', 'd3d12 pass extra resources')
layer = rep(layer, '            dispatch->destroy_swapchain(synthetic.state.handle);\n            synthetic.state.handle = XR_NULL_HANDLE;\n            destroy_current_ring(dispatch, &current);', '            dispatch->destroy_swapchain(synthetic.state.handle); synthetic.state.handle = XR_NULL_HANDLE;\n            for (CreatedPrivateSwapchain& extra : additional_synthetic) if (extra.state.handle != XR_NULL_HANDLE) { static_cast<void>(dispatch->destroy_swapchain(extra.state.handle)); extra.state.handle = XR_NULL_HANDLE; }\n            destroy_current_ring(dispatch, &current);', 'd3d12 failure extras')
layer = rep(layer, '        generation->synthetic = synthetic.state;\n        generation->synthesizer = std::move(synthesizer);', '        generation->synthetic = synthetic.state; synthetic.state.handle = XR_NULL_HANDLE;\n        for (std::size_t i = 0; i < additional_synthetic.size(); ++i) { generation->additional_synthetic[i] = additional_synthetic[i].state; additional_synthetic[i].state.handle = XR_NULL_HANDLE; }\n        generation->synthetic_images_per_slot = synthetic_images_per_slot;\n        generation->synthesizer = std::move(synthesizer);', 'd3d12 adopt extras')
layer = rep(layer, '            if (synthetic.state.handle != XR_NULL_HANDLE) {\n                state->session->dispatch->destroy_swapchain(synthetic.state.handle);\n            }\n            destroy_current_ring(state->session->dispatch, &current);', '            if (synthetic.state.handle != XR_NULL_HANDLE) state->session->dispatch->destroy_swapchain(synthetic.state.handle);\n            for (CreatedPrivateSwapchain& extra : additional_synthetic) if (extra.state.handle != XR_NULL_HANDLE) state->session->dispatch->destroy_swapchain(extra.state.handle);\n            destroy_current_ring(state->session->dispatch, &current);', 'd3d12 catch extras')
layer = rep(layer, '''        const auto destroy_private = [&]() noexcept {\n            if (synthetic.state.handle != XR_NULL_HANDLE) {\n                static_cast<void>(\n                    dispatch->destroy_swapchain(synthetic.state.handle));\n                synthetic.state.handle = XR_NULL_HANDLE;\n            }\n            destroy_current_ring(dispatch, &current);\n        };''', '''        const auto destroy_private = [&]() noexcept {\n            if (synthetic.state.handle != XR_NULL_HANDLE) { static_cast<void>(dispatch->destroy_swapchain(synthetic.state.handle)); synthetic.state.handle = XR_NULL_HANDLE; }\n            for (CreatedPrivateSwapchain& extra : additional_synthetic) if (extra.state.handle != XR_NULL_HANDLE) { static_cast<void>(dispatch->destroy_swapchain(extra.state.handle)); extra.state.handle = XR_NULL_HANDLE; }\n            destroy_current_ring(dispatch, &current);\n        };''', 'd3d11 destroy extras')
old = '''        if (!create_private_swapchain(state, private_info, &synthetic)) {\n            if (failure_reason != nullptr) {\n                *failure_reason =\n                    SwapchainEligibilityReason::synthetic_private_swapchain_failed;\n            }\n            destroy_private();\n            return nullptr;\n        }'''
layer = rep(layer, old, old + '\n        for (CreatedPrivateSwapchain& extra : additional_synthetic) if (!create_private_swapchain(state, private_info, &extra)) { if (failure_reason != nullptr) *failure_reason = SwapchainEligibilityReason::synthetic_private_swapchain_failed; destroy_private(); return nullptr; }', 'd3d11 create extras')
marker = '        auto interop =\n            std::make_shared<xrfg::D3D11D3D12SwapchainInterop>();'
layer = rep(layer, marker, '        std::vector<ID3D11Texture2D*> all_synthetic_d3d11 = synthetic.d3d11_resources;\n        const std::uint32_t synthetic_images_per_slot = static_cast<std::uint32_t>(synthetic.d3d11_resources.size());\n        for (const CreatedPrivateSwapchain& extra : additional_synthetic) { if (extra.d3d11_resources.size() != synthetic.d3d11_resources.size()) { destroy_private(); return nullptr; } all_synthetic_d3d11.insert(all_synthetic_d3d11.end(), extra.d3d11_resources.begin(), extra.d3d11_resources.end()); }\n\n' + marker, 'd3d11 flatten extras')
layer = rep(layer, '            std::span<ID3D11Texture2D* const>(\n                synthetic.d3d11_resources.data(),\n                synthetic.d3d11_resources.size()),', '            std::span<ID3D11Texture2D* const>(all_synthetic_d3d11.data(), all_synthetic_d3d11.size()),', 'd3d11 interop extras')
layer = rep(layer, '        generation->synthetic = synthetic.state;\n        generation->synthesizer = std::move(synthesizer);\n        generation->d3d11_interop = std::move(interop);', '        generation->synthetic = synthetic.state; synthetic.state.handle = XR_NULL_HANDLE;\n        for (std::size_t i = 0; i < additional_synthetic.size(); ++i) { generation->additional_synthetic[i] = additional_synthetic[i].state; additional_synthetic[i].state.handle = XR_NULL_HANDLE; }\n        generation->synthetic_images_per_slot = synthetic_images_per_slot;\n        generation->synthesizer = std::move(synthesizer);\n        generation->d3d11_interop = std::move(interop);', 'd3d11 adopt extras')
layer = rep(layer, '            if (synthetic.state.handle != XR_NULL_HANDLE) {\n                static_cast<void>(state->session->dispatch->destroy_swapchain(\n                    synthetic.state.handle));\n            }\n            destroy_current_ring(state->session->dispatch, &current);', '            if (synthetic.state.handle != XR_NULL_HANDLE) static_cast<void>(state->session->dispatch->destroy_swapchain(synthetic.state.handle));\n            for (CreatedPrivateSwapchain& extra : additional_synthetic) if (extra.state.handle != XR_NULL_HANDLE) static_cast<void>(state->session->dispatch->destroy_swapchain(extra.state.handle));\n            destroy_current_ring(state->session->dispatch, &current);', 'd3d11 catch extras')
layer = rep(layer, '    XrSwapchain current_handle{XR_NULL_HANDLE};\n    XrSwapchain synthetic_handle{XR_NULL_HANDLE};\n    bool anchor_is_current{};', '    XrSwapchain current_handle{XR_NULL_HANDLE};\n    XrSwapchain synthetic_handle{XR_NULL_HANDLE};\n    std::array<XrSwapchain, 2> additional_synthetic_handles{XR_NULL_HANDLE, XR_NULL_HANDLE};\n    std::uint32_t synthetic_count{1};\n    bool anchor_is_current{};', 'prepared handles')
layer = rep(layer, '[[nodiscard]] PreparedGeneration prepare_frame_generation(\n    XrSwapchain application_swapchain,\n    bool request_pair,\n    std::span<const xrfg::D3D12ReprojectionView> current_source_views) noexcept {', '[[nodiscard]] PreparedGeneration prepare_frame_generation(\n    XrSwapchain application_swapchain,\n    bool request_pair,\n    bool request_quad,\n    std::span<const xrfg::D3D12ReprojectionView> current_source_views) noexcept {', 'prepare signature')
layer = rep(layer, '        if (current_image.handle == XR_NULL_HANDLE ||\n            generation->synthetic.handle == XR_NULL_HANDLE ||\n            generation->current_images_per_slot == 0) {', '        if (current_image.handle == XR_NULL_HANDLE || generation->synthetic.handle == XR_NULL_HANDLE || generation->current_images_per_slot == 0 || generation->synthetic_images_per_slot == 0 || (request_quad && (generation->additional_synthetic[0].handle == XR_NULL_HANDLE || generation->additional_synthetic[1].handle == XR_NULL_HANDLE))) {', 'prepare handle validation')
needle = '''        if (request_pair &&\n            !acquire_and_wait_private_image(\n                state->session->dispatch,\n                generation->synthetic)) {\n            output.reason =\n                GenerationPrepareReason::synthetic_private_acquire_failed;\n            static_cast<void>(release_private_image(\n                state->session->dispatch,\n                current_image));\n            std::scoped_lock gpu_lock(state->session->gpu_mutex);\n            static_cast<void>(generation->synthesizer->retire_previous());\n            return output;\n        }'''
layer = rep(layer, needle, needle + '\n        if (request_quad) { for (std::size_t i = 0; i < generation->additional_synthetic.size(); ++i) { if (!acquire_and_wait_private_image(state->session->dispatch, generation->additional_synthetic[i])) { output.reason = GenerationPrepareReason::synthetic_private_acquire_failed; for (std::size_t j = 0; j < i; ++j) static_cast<void>(release_private_image(state->session->dispatch, generation->additional_synthetic[j])); static_cast<void>(release_private_image(state->session->dispatch, generation->synthetic)); static_cast<void>(release_private_image(state->session->dispatch, current_image)); std::scoped_lock gpu_lock(state->session->gpu_mutex); static_cast<void>(generation->synthesizer->retire_previous()); return output; } } }', 'acquire extra synthetic')
needle = '        const std::uint32_t current_destination_index =\n            static_cast<std::uint32_t>(current_slot) *\n                generation->current_images_per_slot +\n            current_image.acquired_index;'
layer = rep(layer, needle, needle + '\n        std::array<std::uint32_t, 3> synthetic_destination_indices{};\n        if (request_pair) { synthetic_destination_indices[0] = generation->synthetic.acquired_index; if (request_quad) for (std::size_t i = 0; i < generation->additional_synthetic.size(); ++i) synthetic_destination_indices[i + 1] = static_cast<std::uint32_t>(i + 1) * generation->synthetic_images_per_slot + generation->additional_synthetic[i].acquired_index; }', 'synthetic indices')
layer = rep(layer, '''                submit_result = request_pair\n                                    ? generation->synthesizer->submit_pair(\n                                          *capture,\n                                          current_source_views,\n                                          current_source_views,\n                                          generation->synthetic.acquired_index,\n                                          current_destination_index,\n                                          &ticket,\n                                          debug_marker,\n                                          motion_vectors)\n                                    : generation->synthesizer->submit_prime(''', '''                submit_result = request_pair\n                                    ? request_quad\n                                        ? generation->synthesizer->submit_quad(*capture, current_source_views, current_source_views, std::span<const std::uint32_t>(synthetic_destination_indices.data(), synthetic_destination_indices.size()), current_destination_index, &ticket, debug_marker, motion_vectors)\n                                        : generation->synthesizer->submit_pair(*capture, current_source_views, current_source_views, generation->synthetic.acquired_index, current_destination_index, &ticket, debug_marker, motion_vectors)\n                                    : generation->synthesizer->submit_prime(''', 'quad submit call')
layer = rep(layer, '''                const HRESULT publish_result =\n                    generation->d3d11_interop->publish(\n                        current_destination_index,\n                        request_pair\n                            ? std::optional<std::uint32_t>(\n                                  generation->synthetic.acquired_index)\n                            : std::nullopt);''', '''                HRESULT publish_result = S_OK;\n                if (!request_pair) publish_result = generation->d3d11_interop->publish(current_destination_index, std::nullopt);\n                else { const std::size_t publish_count = request_quad ? 3U : 1U; for (std::size_t i = 0; i < publish_count && SUCCEEDED(publish_result); ++i) publish_result = generation->d3d11_interop->publish(current_destination_index, synthetic_destination_indices[i]); }''', 'd3d11 publish quad')
layer = rep(layer, '        bool synthetic_released = true;\n        if (request_pair) {\n            synthetic_released = release_private_image(\n                state->session->dispatch,\n                generation->synthetic);\n        }\n        const bool current_released = release_private_image(', '        bool synthetic_released = true;\n        if (request_pair) { synthetic_released = release_private_image(state->session->dispatch, generation->synthetic); if (request_quad) for (PrivateSwapchainState& extra : generation->additional_synthetic) synthetic_released = release_private_image(state->session->dispatch, extra) && synthetic_released; }\n        const bool current_released = release_private_image(', 'release extras')
needle = '        output.anchor_is_current = true;\n        output.current_handle = current_image.handle;\n        output.synthetic_handle = generation->synthetic.handle;'
layer = rep(layer, needle, needle + '\n        output.synthetic_count = request_quad ? 3U : 1U;\n        if (request_quad) { output.additional_synthetic_handles[0] = generation->additional_synthetic[0].handle; output.additional_synthetic_handles[1] = generation->additional_synthetic[1].handle; }', 'output extra handles')
layer = rep(layer, '[[nodiscard]] PreparedProjectionFrame prepare_projection_frame(\n    const ProjectionSnapshot& snapshot,\n    std::span<const ProjectionResourceMapping> mappings,\n    bool request_pair) noexcept {', '[[nodiscard]] PreparedProjectionFrame prepare_projection_frame(\n    const ProjectionSnapshot& snapshot,\n    std::span<const ProjectionResourceMapping> mappings,\n    bool request_pair,\n    bool request_quad) noexcept {', 'projection prepare signature')
layer = rep(layer, '            PreparedGeneration generation = prepare_frame_generation(\n                mapping.application_swapchain,\n                request_pair,\n                std::span<const xrfg::D3D12ReprojectionView>(', '            PreparedGeneration generation = prepare_frame_generation(\n                mapping.application_swapchain,\n                request_pair,\n                request_quad,\n                std::span<const xrfg::D3D12ReprojectionView>(', 'projection prepare forward')
marker = '[[nodiscard]] bool capture_projection_snapshot(\n'
layer = insert_before(layer, marker, '''[[nodiscard]] XrResult enqueue_presenter_quad(const std::shared_ptr<SessionState>& state, std::shared_ptr<GeneratedFrameEndInfo> first, std::shared_ptr<GeneratedFrameEndInfo> second, std::shared_ptr<GeneratedFrameEndInfo> third, std::shared_ptr<GeneratedFrameEndInfo> current) noexcept {\n    try { std::scoped_lock lock(state->presenter_mutex); if (!state->presenter_active || state->presenter_stop_requested || XR_FAILED(state->presenter_failure)) return XR_FAILED(state->presenter_failure) ? state->presenter_failure : XR_ERROR_SESSION_NOT_RUNNING;\n        std::array<std::shared_ptr<GeneratedFrameEndInfo>, 4> frames{std::move(first), std::move(second), std::move(third), std::move(current)}; for (auto& frame : frames) { auto request = std::make_shared<PresenterSubmission>(); request->sequence = state->next_presenter_sequence++; request->owned_frame = std::move(frame); state->presenter_submissions.push_back(std::move(request)); } state->outstanding_presenter_submissions += frames.size(); state->presenter_condition.notify_all(); return XR_SUCCESS; } catch (...) { return XR_ERROR_OUT_OF_MEMORY; }\n}\n\n''', 'quad presenter helper')
layer = rep(layer, '''[[nodiscard]] XrDuration doubled_display_period(XrDuration period) noexcept {\n    if (period <= 0) {\n        return period;\n    }\n    constexpr XrDuration maximum = std::numeric_limits<XrDuration>::max();\n    return period > maximum / 2 ? maximum : period * 2;\n}''', '''[[nodiscard]] XrDuration multiplied_display_period(XrDuration period, std::uint32_t multiplier) noexcept { if (period <= 0 || multiplier <= 1U) return period; constexpr XrDuration maximum = std::numeric_limits<XrDuration>::max(); return period > maximum / static_cast<XrDuration>(multiplier) ? maximum : period * static_cast<XrDuration>(multiplier); }\n[[nodiscard]] XrDuration generated_application_period(const std::shared_ptr<SessionState>& state, XrDuration period) noexcept { return multiplied_display_period(period, state && state->optical_flow_backend == xrfg::D3D12OpticalFlowBackend::nvidia ? 4U : 2U); }''', 'period multiplier')
layer = layer.replace('doubled_display_period(state->presenter_frame_state.predictedDisplayPeriod)', 'generated_application_period(state, state->presenter_frame_state.predictedDisplayPeriod)', 1).replace('doubled_display_period(state->last_inline_frame_state.predictedDisplayPeriod)', 'generated_application_period(state, state->last_inline_frame_state.predictedDisplayPeriod)', 1)
layer = rep(layer, '''    PreparedProjectionFrame prepared = prepare_projection_frame(\n        current_snapshot,\n        std::span<const ProjectionResourceMapping>(\n            resource_mappings.mappings.data(),\n            resource_mappings.mappings.size()),\n        metadata_pairable);''', '''    const bool request_quad = metadata_pairable && use_continuous_presenter && state->optical_flow_backend == xrfg::D3D12OpticalFlowBackend::nvidia;\n    PreparedProjectionFrame prepared = prepare_projection_frame(\n        current_snapshot, std::span<const ProjectionResourceMapping>(resource_mappings.mappings.data(), resource_mappings.mappings.size()), metadata_pairable, request_quad);''', 'prepare quad call')
layer = rep(layer, '    std::vector<ProjectionResourceDestination> current_destinations;\n    std::vector<ProjectionResourceDestination> synthetic_destinations;\n    current_destinations.reserve(prepared.resources.size());\n    synthetic_destinations.reserve(prepared.resources.size());', '    std::vector<ProjectionResourceDestination> current_destinations;\n    std::vector<ProjectionResourceDestination> synthetic_destinations;\n    std::array<std::vector<ProjectionResourceDestination>, 2> additional_synthetic_destinations;\n    current_destinations.reserve(prepared.resources.size()); synthetic_destinations.reserve(prepared.resources.size()); for (auto& destinations : additional_synthetic_destinations) destinations.reserve(prepared.resources.size());', 'destination vectors')
needle = '        synthetic_destinations.push_back({\n            resource.application_swapchain,\n            resource.generation.synthetic_handle,\n        });'
layer = rep(layer, needle, needle + '\n        if (resource.generation.synthetic_count == 3U) for (std::size_t i = 0; i < additional_synthetic_destinations.size(); ++i) additional_synthetic_destinations[i].push_back({resource.application_swapchain, resource.generation.additional_synthetic_handles[i]});', 'extra destination push')
layer = rep(layer, '    GeneratedFrameEndInfo first_generated{};\n    GeneratedFrameEndInfo current_generated{};\n    const XrFrameEndInfo* submitted_end_info = end_info;\n    bool pair_ready = false;', '    GeneratedFrameEndInfo first_generated{}; std::array<GeneratedFrameEndInfo, 2> additional_generated{};\n    GeneratedFrameEndInfo current_generated{};\n    const XrFrameEndInfo* submitted_end_info = end_info;\n    bool pair_ready = false; bool quad_ready = false;', 'generated frames')
layer = rep(layer, '''        const bool current_built = build_generated_frame_end_info(\n            end_info,\n            current_snapshot,\n            false,\n            std::span<const ProjectionResourceDestination>(\n                current_destinations.data(), current_destinations.size()),\n            &current_generated);\n        if (synthetic_built && current_built) {\n            submitted_end_info = &first_generated.info;\n            pair_ready = true;\n        } else {''', '''        const bool current_built = build_generated_frame_end_info(end_info, current_snapshot, false, std::span<const ProjectionResourceDestination>(current_destinations.data(), current_destinations.size()), &current_generated);\n        bool additional_built = true; const bool all_quad_resources = request_quad && std::all_of(prepared.resources.begin(), prepared.resources.end(), [](const PreparedProjectionResource& resource) { return resource.generation.synthetic_count == 3U; });\n        if (all_quad_resources) for (std::size_t i = 0; i < additional_generated.size(); ++i) additional_built = additional_built && build_generated_frame_end_info(end_info, current_snapshot, true, std::span<const ProjectionResourceDestination>(additional_synthetic_destinations[i].data(), additional_synthetic_destinations[i].size()), &additional_generated[i]);\n        if (synthetic_built && current_built && additional_built) { submitted_end_info = &first_generated.info; pair_ready = true; quad_ready = all_quad_resources; } else {''', 'build quad frames')
layer = rep(layer, '    std::shared_ptr<GeneratedFrameEndInfo> presenter_first_frame;\n    first_generated.synthetic = pair_ready;\n    std::shared_ptr<GeneratedFrameEndInfo> presenter_current_frame;', '    std::shared_ptr<GeneratedFrameEndInfo> presenter_first_frame; first_generated.synthetic = pair_ready; for (GeneratedFrameEndInfo& generated : additional_generated) generated.synthetic = quad_ready;\n    std::array<std::shared_ptr<GeneratedFrameEndInfo>, 2> presenter_additional_frames{};\n    std::shared_ptr<GeneratedFrameEndInfo> presenter_current_frame;', 'presenter frame pointers')
layer = rep(layer, '        if (pair_ready) {\n            presenter_current_frame =\n                make_presenter_owned_frame(std::move(current_generated));\n        }', '        if (pair_ready) { if (quad_ready) for (std::size_t i = 0; i < presenter_additional_frames.size(); ++i) presenter_additional_frames[i] = make_presenter_owned_frame(std::move(additional_generated[i])); presenter_current_frame = make_presenter_owned_frame(std::move(current_generated)); }', 'own quad frames')
layer = rep(layer, '        if (!presenter_first_frame ||\n            (pair_ready && !presenter_current_frame)) {', '        if (!presenter_first_frame || (pair_ready && !presenter_current_frame) || (quad_ready && (!presenter_additional_frames[0] || !presenter_additional_frames[1]))) {', 'validate quad owned')
layer = rep(layer, '        if (pair_ready) {\n            result = enqueue_presenter_pair(\n                state,\n                presenter_first_frame,\n                presenter_current_frame);', '        if (pair_ready) {\n            result = quad_ready ? enqueue_presenter_quad(state, presenter_first_frame, presenter_additional_frames[0], presenter_additional_frames[1], presenter_current_frame) : enqueue_presenter_pair(state, presenter_first_frame, presenter_current_frame);', 'enqueue quad')
layer = layer.replace('                result = wait_for_presenter_capacity(state, 2);', '                result = wait_for_presenter_capacity(state, quad_ready ? 4 : 2);', 1)
layer = rep(layer, '    } else if (steamvr_wait_requires_continuous_presenter(\n                   state,\n                   current_cycle)) {', '    } else if (state->dispatch->steamvr_runtime && state->optical_flow_backend == xrfg::D3D12OpticalFlowBackend::nvidia) {\n        state->steamvr_presenter_start_requested = true;\n    } else if (steamvr_wait_requires_continuous_presenter(\n                   state,\n                   current_cycle)) {', 'force nvidia presenter')
write(layer_path, layer)

print('OFXR 4x prototype patch applied successfully')
